# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 윤호진
title: 1998.03.28.
email: yhj14531@gmail.com
Tel: 010-4746-1453
website: https://www.notion.so/Hojin-Yoon-c4d882a41ab94ec6b739af49d160552c

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  henryoon
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: _yhoijn_
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/hojin.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. 저는 지능형 로봇 시스템을 연구하는 기계공학과 석사입니다. 다양한 센서와 알고리즘을 통합하여 산업 및 물류 환경에서 실제로 동작 가능한 로봇 시스템을 설계·구현하는 데에 관심이 많습니다.

  석사 과정동안 수행한 주요 연구 과제는 ‘산업 분야에서의 지능로봇 시스템 통합 및 자동화’이며 RGB-D camera, IMU, LiDAR, manipulator를 탑재한 로봇 플랫폼을 기반으로 도/소매, 제조, 물류 환경에서 로봇 시스템의 통합을 목표로 했습니다.

  저는 <mark>제어</mark>, <mark>로봇 비전</mark>, <mark>Visual SLAM</mark> 파트에 강점을 지니고 있습니다.

content:
  - title: Education (University) # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 숭실대학교
        caption: 2017.03 - 2023.02
        sub_title: 기계공학부
        quote: >
          학사 졸업 논문: RGB-D 카메라 탑재 협동형 머니퓰레이터 기반의 팔레트 상에 무작위로 배열된 공작물의 선택적 픽 앤 플레이스 구현 방법
        description: | # this will include new lines to allow paragraphs
          학부 3학년 때 '국제 대학생 창작 자동차 경진대회'를 준비하면서 자율주행 시스템 개발 프로젝트를 진행했습니다. 해당 프로젝트에서 <strong>Controller</strong>, <strong>Object Detection</strong>, <strong>SLAM</strong> 파트를 담당했으며, 제어 정확도 및 물체 인식 정확도 모두 <strong>90%</strong> 이상 달성한 성과를 거두었습니다.

          학부 4학년 때 지능형 로봇 시스템 연구실의 학부 인턴으로 있으면서 '로봇 제조 공정 활용 경진대회'를 참가했습니다. 해당 경진대회를 준비하면서 <strong>Object Detection</strong>, <strong>Path Planning</strong>을 담당했으며, 12개의 공작물을 pick-and-place하는데 첫 시도(4분대) 대비 약 <strong>50%</strong> 단축 시킨 성과를 거두었습니다.

  - title: Education (Graduate School)
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 숭실대학교 일반대학원
        caption: 2023.03 - 2025.02
        sub_title: 기계공학과
        quote: >
          석사 졸업 논문: 가상 현실 기반 원격 제어 시 가상-실제 로봇 간 자세 추정 불일치 최소화 방법에 관한 연구
        description: | # this will include new lines to allow paragraphs
          지능형 로봇 시스템 연구실에서 '디지털 트윈 기반 물류 핸들링' 연구를 수행했습니다. 해당 연구는 <strong>메커니즘</strong>, 인공지능, <strong>원격지휘</strong>, 테스트 벤치 분야로 구분되어 수행되었으며, 이 중 <strong>메커니즘(모바일 매니퓰레이션 및 피킹 메커니즘)</strong>과 <strong>원격지휘(로봇 운영 딜레마 극복을 위한 원격제어 인터페이스)</strong>를 주로 담당하며 연구를 수행했습니다.

          석사 졸업 논문의 주제는 <strong>로봇 자세 추정 정확도 향상을 위해 3단계로 구성된 방법을 제안</strong>하는 것입니다. 
          3단계: 1. YOLO v11 instance segmentation을 통한 객체 인식, 2. 원격 제어자의 의도 파악 알고리즘을 통한 목표 상자 식별, 3. 목표 상자 기준 로봇 자세 업데이트.
          기존 실내 로봇 자세 추정 알고리즘인 Landmark-based localization 대비 불일치율이 <strong>87.5%</strong> 감소했으며, 작업 성공률이 <strong>30%</strong> 향상되는 성과를 거두었습니다.

  - title: Research Experience
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 지능형로봇시스템 LAB
        caption: 2021. - 2024.
        sub_title: 이동훈 교수
        description: | # this will include new lines to allow paragraphs
          지능로봇 시스템의 자동화 부문 연구를 진행하고 있으며 로보틱스, 인공지능 등 다양한 분야에 지식이 있습니다. 주요연구과제는 <strong>‘산업 분야에서의 지능로봇 시스템 통합 및 자동화’</strong>이며 RGB-D camera, IMU, LiDAR, manipulator를 탑재한 로봇 플랫폼을 기반으로 도/소매, 제조, 물류 환경에서 로봇 시스템의 통합을 목표로 합니다. 주요 연구의 기반을 다지기 위해 다음과 같은 역량을 쌓았습니다.
          - <strong>실시간 인식 알고리즘 최적화를 통한 주변 환경/물체 인식 정확도 90% 이상 달성</strong><br>
          ‘2021 국제 대학생 창작자동차 경진대회’를 준비하며 SLAM, camera - 3D LiDAR fusion, YOLO v4와 같은 실시간 주변 환경/물체 인식 알고리즘을 활용하여 인식 정확도를 향상시키는 방법에 대해 고찰했습니다. 각 알고리즘의 파라미터 최적화를 진행한 결과 localization 및 물체 인식 정확도 모두 90% 이상 달성하는 성과를 보였습니다.
          - <strong>객체 인식 및 task/path planning 최적화를 통한 공작물의 pick-and-place 수행 시간 50% 단축</strong><br>
          ‘2022 로봇제조공정활용 경진대회’에 참가하여 3가지 모양의 공작물 12개를 빠르고 정확하게 목표 지점까지 이동시키는 프로젝트를 진행했습니다. YOLO, OpenCV와 같은 물체 인식 알고리즘을 활용하여 공작물을 인식하고 최적의 task/path planning 방법을 고안하여 첫 시도 ‘4분대’에서 최종 ‘2분 14초’로 약 50% 단축하는 성과를 보였습니다.
          - <strong>선형 및 각도 scaling parameter 최적화를 통한 원격 manipulation 정확도 80% 이상 달성</strong><br>
          먼저 총 3개의 IMU 센서를 어깨/손목 관절 및 요추에 부착하여 기준 좌표계를 만들었습니다. 다음 팔을 움직일 때의 센서 데이터-가속도 값을 활용하여 팔의 움직임을 모방하는 manipulator의 원격 제어 방법에 대해 고찰했습니다. 팔의 움직임과 manipulator의 움직임 정도가 다르기 때문에 선형 및 각도 scaling parameter의 최적화도 진행했습니다. 제안한 방법의 성능은 손과 manipulator end-effector에 motion capture markers를 부착하여 궤적의 비교로 평가했습니다. 평가 결과 실제 팔의 움직임과 manipulator의 움직임의 유사성이 80% 이상으로 나타나는 성과를 보였습니다.
          - <strong>가상환경 구축을 통해 로봇을 원격 제어 하는 작업자에게 몰입감을 부여하여 단순 카메라를 사용하는 경우에 비해 작업시간 20% 단축</strong><br>
          RGB-D 카메라와 mobile manipulator를 사용하여 작업 환경을 3D map으로 생성하여 가상환경을 구축했습니다. 이는 카메라 화면과 비교했을 때 공간감을 부여할 수 있다는 장점이 있어 작업 시 좀 더 몰입감을 느낄 수 있다는 장점이 있습니다. 또한 가상환경을 실시간으로 업데이트 해주는 새로운 접근 방식으로 작업자의 몰입감을 한 층 더 높여 최종적으로는 작업시간을 20% 단축시키는 성과를 보였습니다.
          - <strong>가상-실제 로봇 자세 추정 불일치 87.5% 개선</strong><br>
          Point Cloud Data로 구성된 3D RGB map에 대하여 기존의 'Visual landmark-based Visual-Inertial Wheel Odometry' 로봇 자세 추정 방식에 비해 높은 정확도를 가지는 방법을 제안했습니다. 모바일 매니퓰레이터 원격 제어를 하는 동안 움직임 데이터를 분석하여 실시간으로 제어자가 집으려는 물체를 식별하고, 식별 된 물체를 기준으로 모바일 매니퓰레이터의 자세를 정밀하게 추정하여 기존 방법 대비 정확도를 87.5% 개선하는 성과를 보였습니다.

  - title: Academic Publications & Copyrights
    layout: text
    content: |
      <span style="font-size:16px;"><strong>2022.12.</strong> 'RGB-D 카메라 탑재 협동형 매니퓰레이터 기반의 팔레트 상에 무작위로 배열된 공작물의 선택적 픽 앤 플레이스 구현 방법'</span><br>
      <span style="font-size:14px;">[학사 졸업 논문]</span><br><br>

      <span style="font-size:16px;"><strong>2024.01.08.</strong> 'A Decade of Progress in Human Motion Recognition: A Comprehensive Survey from 2010 to 2020'</span><br>
      <span style="font-size:14px;">[IEEE Access]</span><br><br>

      <span style="font-size:16px;"><strong>2024.12.</strong> '가상 현실 기반 원격제어 시 가상-실제 로봇 간 자세 추정 불일치 최소화 방법에 관한 연구'</span><br>
      <span style="font-size:14px;">[석사 졸업 논문]</span><br><br>

      <span style="font-size:16px;"><strong>2025.02.11.</strong> 'Structural Stability Assessment for Optimal Order Picking in Box-Stacked Storage Logistics'</span><br>
      <span style="font-size:14px;">[MDPI Sensors]</span><br><br>

      <span style="font-size:16px;"><strong>2025.02.17.</strong> 'A Semi-Autonomous Telemanipulation Order-Picking Control Based on Estimating Operator Intent for Box-Stacking Storage Environment'</span><br>
      <span style="font-size:14px;">[MDPI Sensors]</span><br><br>
      
      <span style="font-size:16px;"><strong>2023.12.29.</strong> '물류창고 어플리케이션의 디지털 트윈을 위한 실시간 로컬 시각적 지도 업데이트'</span><br>
      <span style="font-size:14px;">[저작권]</span><br><br>

      <span style="font-size:16px;"><strong>2023.12.29.</strong> '물류창고, 대형마트, 병원/가정 등의 분야별 작업 시나리오 맞춤형 다중물류 인식 기술'</span><br>
      <span style="font-size:14px;">[저작권]</span><br><br>
      
      <span style="font-size:16px;"><strong>2024.12.20.</strong> '원격 제어자의 움직임 분석을 통한 목표 물체 식별 기술'</span><br>
      <span style="font-size:14px;">[저작권]</span>

  - title: Awards
    layout: text
    content: |
      <span style="font-size:16px;"><strong>2021.10.04.</strong> '국제 대학생 창작 자동차 경진대회'</span><br>
      <span style="font-size:14px;">자율주행자동차 창작기술부문 우수상 [한국자동차안전학회]</span><br><br>

      <span style="font-size:16px;"><strong>2022.04.28.</strong> '대한기계학회 2021 학술대회'</span><br>
      <span style="font-size:14px;">우수논문상 [대한기계학회]</span><br><br>

      <span style="font-size:16px;"><strong>2022.11.28.</strong> '로봇제조공정활용 경진대회'</span><br>
      <span style="font-size:14px;">최우수상 [한국전자기술연구원, 한국로봇학회]</span><br><br>

      <span style="font-size:16px;"><strong>2022.12.14.</strong> '제 12회 숭실공학상'</span><br>
      <span style="font-size:14px;">우수상 [숭실대학교]</span>

  - title: Certificate
    layout: text
    content: |
      <span style="font-size:16px;"><strong>2016.12.27.</strong> '자동차운전면허'</span><br>
      <span style="font-size:14px;">1종 보통 [서울특별시경찰청]</span><br><br>

      <span style="font-size:16px;"><strong>2019.12.02.</strong> '지게차운전기능사'</span><br>
      <span style="font-size:14px;">[한국산업인력공단]</span><br><br>

      <span style="font-size:16px;"><strong>2024.10.27.</strong> 'TOEIC SPEAKING'</span><br>
      <span style="font-size:14px;">AL 160 [ETS]</span>

  - title: Extracurricular Activities
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ACCA
        caption: 2021.03 - 2022.12
        sub_title: 학회 활동
        description: | # this will include new lines to allow paragraphs
          자율주행을 위한 제어기 및 물체 인식 알고리즘 개발
          - Controller: Speed controller, stanley method를 사용하여 ERP42의 신호 제어 및 제어 동작 수행
          - Object detection: RGB-D camera & 3D LiDAR fusion을 통한 물체 인식
          - SLAM: LIO-SAM 알고리즘 기반의 point cloud map 생성 최적화

  - title: Volunteer Experience
    layout: text
    content: |
      <span style="font-size:16px;"><strong>2021.04. ~ 2021.04. 양천중앙도서관</strong></span><br>
      <span style="font-size:14px;">방문자 발열체크, 자료실 책 소독 및 자료 정리 [20h]</span>
  
  - title: Military service Volunteer Experience
    layout: text
    content: |
      <span style="font-size:16px;"><strong>2018.06.25. ~ 2020.05.07</strong></span><br>
      <span style="font-size:14px;">공군 만기전역</span>

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <strong>React</strong> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 2021.10.04. '국제 대학생 창작 자동차 경진대회' 자율주행자동차 창작기술부문 우수상 [한국자동차안전학회]
      - 2022.04.28. '대한기계학회 2021 학술대회' 우수논문상 [대한기계학회]
      - 2022.11.28. '로봇제조공정활용 경진대회' 최우수상 [한국전자기술연구원, 한국로봇학회]
      - 2022.12.14. '제 12회 숭실공학상' 우수상 [숭실대학교]
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
