# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 윤호진
title: Robotics Engineer
email: yhj14531@gmail.com
website: https://www.notion.so/Hojin-Yoon-c4d882a41ab94ec6b739af49d160552c

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  henryoon
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: _yhoijn_
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/hojin.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. 저는 지능형 로봇 시스템을 연구하는 기계공학과 석사입니다. 다양한 센서와 알고리즘을 통합하여 산업 및 물류 환경에서 실제로 동작 가능한 로봇 시스템을 설계·구현하는 데에 관심이 많습니다.

  석사 과정동안 수행한 주요 연구 과제는 ‘산업 분야에서의 지능로봇 시스템 통합 및 자동화’이며 RGB-D camera, IMU, LiDAR, manipulator를 탑재한 로봇 플랫폼을 기반으로 도/소매, 제조, 물류 환경에서 로봇 시스템의 통합을 목표로 했습니다.

  저는 <mark>제어</mark>, <mark>로봇 비전</mark>, <mark>Visual SLAM</mark> 파트에 강점을 지니고 있습니다.

content:
  - title: Education (University) # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 숭실대학교
        caption: 2017.03 - 2023.02
        sub_title: 기계공학부
        quote: >
          학사 졸업 논문: RGB-D 카메라 탑재 협동형 머니퓰레이터 기반의 팔레트 상에 무작위로 배열된 공작물의 선택적 픽 앤 플레이스 구현 방법
        description: | # this will include new lines to allow paragraphs
          학부 3학년 때 '국제 대학생 창작 자동차 경진대회'를 준비하면서 자율주행 시스템 개발 프로젝트를 진행했습니다. 해당 프로젝트에서 <strong>Controller</strong>, <strong>Object Detection</strong>, <strong>SLAM</strong> 파트를 담당했으며, 제어 정확도 및 물체 인식 정확도 모두 <strong>90%</strong> 이상 달성한 성과를 거두었습니다.

          학부 4학년 때 지능형 로봇 시스템 연구실의 학부 인턴으로 있으면서 '로봇 제조 공정 활용 경진대회'를 참가했습니다. 해당 경진대회를 준비하면서 <strong>Object Detection</strong>, <strong>Path Planning</strong>을 담당했으며, 12개의 공작물을 pick-and-place하는데 첫 시도(4분대) 대비 약 <strong>50%</strong> 단축 시킨 성과를 거두었습니다.

  - title: Education (Graduate School)
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 숭실대학교 일반대학원
        caption: 2023.03 - 2025.02
        sub_title: 기계공학과
        quote: >
          석사 졸업 논문: 가상 현실 기반 원격 제어 시 가상-실제 로봇 간 자세 추정 불일치 최소화 방법에 관한 연구
        description: | # this will include new lines to allow paragraphs
          지능형 로봇 시스템 연구실에서 '디지털 트윈 기반 물류 핸들링' 연구를 수행했습니다. 해당 연구는 <strong>메커니즘</strong>, 인공지능, <strong>원격지휘</strong>, 테스트 벤치 분야로 구분되어 수행되었으며, 이 중 <strong>메커니즘(모바일 매니퓰레이션 및 피킹 메커니즘)</strong>과 <strong>원격지휘(로봇 운영 딜레마 극복을 위한 원격제어 인터페이스)</strong>를 주로 담당하며 연구를 수행했습니다.

          석사 졸업 논문의 주제는 <strong>로봇 자세 추정 정확도 향상을 위해 3단계로 구성된 방법을 제안</strong>하는 것입니다. 
          3단계: 1. YOLO v11 instance segmentation을 통한 객체 인식, 2. 원격 제어자의 의도 파악 알고리즘을 통한 목표 상자 식별, 3. 목표 상자 기준 로봇 자세 업데이트.
          기존 실내 로봇 자세 추정 알고리즘인 Landmark-based localization 대비 불일치율이 <strong>87.5%</strong> 감소했으며, 작업 성공률이 <strong>30%</strong> 향상되는 성과를 거두었습니다.

  - title: Awards
    layout: text
    content: |
      <span style="font-size:16px;"><strong>2021.10.04.</strong> '국제 대학생 창작 자동차 경진대회'</span><br>
      <span style="font-size:14px;">자율주행자동차 창작기술부문 우수상 [한국자동차안전학회]</span><br><br>

      <span style="font-size:16px;"><strong>2022.04.28.</strong> '대한기계학회 2021 학술대회'</span><br>
      <span style="font-size:14px;">우수논문상 [대한기계학회]</span><br><br>

      <span style="font-size:16px;"><strong>2022.11.28.</strong> '로봇제조공정활용 경진대회'</span><br>
      <span style="font-size:14px;">최우수상 [한국전자기술연구원, 한국로봇학회]</span><br><br>

      <span style="font-size:16px;"><strong>2022.12.14.</strong> '제 12회 숭실공학상'</span><br>
      <span style="font-size:14px;">우수상 [숭실대학교]</span>

  - title: Academic Publications & Copyrights
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <strong>React</strong> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 2021.10.04. '국제 대학생 창작 자동차 경진대회' 자율주행자동차 창작기술부문 우수상 [한국자동차안전학회]
      - 2022.04.28. '대한기계학회 2021 학술대회' 우수논문상 [대한기계학회]
      - 2022.11.28. '로봇제조공정활용 경진대회' 최우수상 [한국전자기술연구원, 한국로봇학회]
      - 2022.12.14. '제 12회 숭실공학상' 우수상 [숭실대학교]
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
